### Post counter
POST http://localhost:8080/update/counter/someMetric/527
Content-Type: text/plain

### Post gauge
POST http://localhost:8080/update/gauge/someMetric/527
Content-Type: text/plain

### Post gauge
POST http://localhost:8080/update/counter/someMetric2/dd
Content-Type: text/plain

### GET request with a header
GET http://localhost:8080/update/gauge/someMetric2/527
Accept: text/plain

### GET
GET http://localhost:8080/
Accept: text/plain

### GET
GET http://localhost:8080/value/counter/someMetric2
Accept: text/plain

###Post Json update
POST http://localhost:8080/update/
Content-Type: application/json

{
  "id": "LastGC2",
  "type": "counter",
  "delta": 45
}

###Post Json value
POST http://localhost:8080/value/
Content-Type: application/json

{
  "id": "LastGC2",
  "type": "counter"

}